namespace ServiceInterfaces
{
    public interface IItemDAO
    {
        /*
         * Amazing opportunity to make an interface
         * for partial class generated by Entity Framework
         * (see Partials\tblItem.cs)
         */

        /// <summary>
        /// Item ID
        /// </summary>
        long ID { get; set; }

        /// <summary>
        /// Item name
        /// </summary>
        string Name { get; set; }

        /// <summary>
        /// Item parameter A
        /// </summary>
        double ParameterA { get; set; }

        /// <summary>
        /// Item parameter B
        /// </summary>
        double ParameterB { get; set; }
    }
}
