//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItem
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public double ParameterA { get; set; }
        public double ParameterB { get; set; }
    }
}
